### ISSUE TITLE
data.sha can be undefined at View diff button

### ISSUE THREAD

**Issue by ilsubyeega** [typesense/showcase-linux-commits-search#1]
## Description
https://github.com/typesense/showcase-linux-commits-search/blob/c781341b83b4459c150674e03568e654e5883c2d/src/app.js#L212

https://linux-commits-search.typesense.org/?commits%5Bquery%5D=minecraft
click `View Diff` on commit `628e04dfeb4f66635c0d22cf1ad0cf427406e129` 

## Expected Behavior
Should be gone to `https://github.com/torvalds/linux/commit/628e04dfeb4f66635c0d22cf1ad0cf427406e129`

## Actual Behavior
Actually it goes to `https://github.com/torvalds/linux/commit/undefined`

**Comment by jasonbosco** [comment]
Resolved by #2
